blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.all_blogs, name="all_blogs"),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('blog/', include('blog.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home')
]

blog/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()

portfolio/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.


def all_blogs(request):
    blogs = Blog.objects.order_by('-date')[:5]
    return render(request, 'blog/all_blogs.html', {'blogs': blogs})

def detail(request,blog_id):
    blog_detail = get_object_or_404(Blog, pk=blog_id)
    return render(request,'blog/detail.html',{'blog_detail':blog_detail})

portfolio/views.py
from django.shortcuts import render
from .models import Project


def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html',{'projects':projects})

blog/templates/blog/all_blogs.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Blog Page</title>
	</head>
	<body>
		<h1>Most recent Blogs</h1>
		{% for blog in blogs %}
		<a href="{% url 'blog:detail' blog.id %}"><h2>{{ blog.title }}</h2></a>
		<h3>{{ blog.date }}</h3>
		{% endfor %}
	</body>
</html>

blog/templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Blog Details</title>
	</head>
	<body>
		<h2>{{ blog_detail.title }}</h2>
		<p>{{ blog_detail.description }}</p>
	</body>
</html>

portfolio/templates/portfolio/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Home Page</title>
	</head>
	<body>
		<h2>This is Rakibul's Portfolio</h2>
		<a href="{% static 'portfolio_file/Rakibul_Islam.pdf' %}"
			>Resume of Rakibul</a
		>
		<img
			src="{% static 'portfolio_file/profile_pic.JPG' %}"
			alt="profile pic"
		/>
		{% for project in projects %}
		<h2>{{ project.title }}</h2>
		<p>{{ project.description }}</p>
		<img src="{{ project.image.url }}" alt="{{ project.title }}" />

		{% if project.url %}
		<a href="{{ project.url }}">Link</a>
		{% endif %} {% endfor %}
	</body>
</html>